# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: febf86a8ea6511ac572bb5db377653e63234ef368c13eee8c53f69fe8cc23fb57348358fa99c132b4bd8aaefa663300c6e8009ffc2e0b031e2c2d5816de7802f

test:
  secret_key_base: 7d802a38d65ecd95da82eda9f16048c85ce55808f1736d0bc6ff8bd70960d99fb22522ad2c6982eaff16d705ca8fbe288c32d547bf017e8d25fbff94bbfe1afc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
